/**
 * seedLegalContent.js
 *
 * Reads parsedLaws.json (generated by parsePenalCode.js) and inserts
 * the articles into the MongoDB LegalContent collection.
 *
 * Usage:
 *   node backend/seedLegalContent.js
 *
 * Options:
 *   --clear   Drop all existing LegalContent documents before seeding
 */

import mongoose from 'mongoose'
import fs from 'fs'
import path from 'path'
import { fileURLToPath } from 'url'
import dotenv from 'dotenv'

const __filename = fileURLToPath(import.meta.url)
const __dirname = path.dirname(__filename)

dotenv.config({ path: path.join(__dirname, '.env') })

const PARSED_LAWS_PATH = path.join(__dirname, '..', 'Documents', 'parsedLaws.json')
const CLEAR_FLAG = process.argv.includes('--clear')

// ─── LegalContent Schema (inline to avoid circular deps) ─────────────────────

import LegalContent from './src/models/LegalContent.js'

// ─── Seeder Logic ─────────────────────────────────────────────────────────────

async function seed() {
  console.log('━'.repeat(60))
  console.log('  Digital Legal Aid — LegalContent Seeder')
  console.log('━'.repeat(60))

  // Connect to MongoDB
  const mongoUri = process.env.MONGODB_URI
  if (!mongoUri) {
    console.error('❌ MONGODB_URI not found in .env file')
    console.error('   Make sure backend/.env exists with MONGODB_URI set.')
    process.exit(1)
  }

  console.log(`\n🔌 Connecting to MongoDB...`)
  await mongoose.connect(mongoUri)
  console.log('✅ Connected to MongoDB\n')

  // Read parsedLaws.json
  if (!fs.existsSync(PARSED_LAWS_PATH)) {
    console.error(`❌ parsedLaws.json not found at: ${PARSED_LAWS_PATH}`)
    console.error('   Run parsePenalCode.js first: node backend/parsePenalCode.js Documents/penalcode2018.pdf')
    await mongoose.disconnect()
    process.exit(1)
  }

  const raw = fs.readFileSync(PARSED_LAWS_PATH, 'utf8')
  const { metadata, articles } = JSON.parse(raw)

  console.log(`📋 Source: ${metadata.source}`)
  console.log(`📋 Parsed at: ${metadata.parsed_at}`)
  console.log(`📋 Total articles to seed: ${articles.length}\n`)

  // Optionally clear existing data
  if (CLEAR_FLAG) {
    const deleted = await LegalContent.deleteMany({})
    console.log(`🗑️  Cleared ${deleted.deletedCount} existing LegalContent documents\n`)
  }

  // Map validated crime types (LegalContent schema enum)
  const VALID_CRIME_TYPES = new Set([
    'Theft', 'Assault', 'GBV', 'Fraud', 'Property Damage',
    'Murder', 'Drug', 'Corruption', 'Other'
  ])

  // Build LegalContent documents from parsed articles
  const documents = articles.map(article => ({
    crimeType: VALID_CRIME_TYPES.has(article.crime_type) ? article.crime_type : 'Other',
    articleNumber: article.article_number,
    originalText: {
      en: article.english_text,
      rw: article.kinyarwanda_text || ''
    },
    simplifiedExplanation: {
      en: article.simplified_english,
      rw: article.kinyarwanda_text
        ? article.kinyarwanda_text.substring(0, 300) + '...'
        : article.simplified_english
    },
    reportingSteps: article.reporting_steps.map(step => ({
      stepNumber: step.step_number,
      description: {
        en: step.description,
        rw: step.description  // Will be updated with proper translations later
      }
    })),
    requiredEvidence: article.required_evidence.map(evidence => ({
      en: evidence,
      rw: evidence  // Will be updated with proper translations later
    })),
    whereToReport: {
      en: article.where_to_report,
      rw: article.where_to_report  // Will be updated with proper translations later
    },
    tags: article.keywords || [],
    keywords: article.keywords || [],
    viewCount: 0
  }))

  // Use bulkWrite with ordered:false for fast upserts — skips duplicates automatically
  console.log('⏳ Inserting into MongoDB (bulk upsert)...')

  const ops = documents.map(doc => ({
    updateOne: {
      filter: { articleNumber: doc.articleNumber },
      update: { $setOnInsert: doc },
      upsert: true
    }
  }))

  const result = await LegalContent.bulkWrite(ops, { ordered: false })

  const inserted = result.upsertedCount
  const skipped = documents.length - inserted

  console.log('📊 Seeding results:')
  console.log(`   ✅ Inserted: ${inserted} new articles`)
  console.log(`   ⏭️  Skipped (already exist): ${skipped} articles`)

  const total = await LegalContent.countDocuments()
  console.log(`\n📦 Total LegalContent documents in DB: ${total}`)

  await mongoose.disconnect()
  console.log('\n✅ Done. MongoDB disconnected.\n')
}

seed().catch(err => {
  console.error('❌ Seeder failed:', err.message)
  console.error(err.stack)
  process.exit(1)
})
