/**
 * seedLegalContent.js
 *
 * Reads parsedLaws.json (generated by parsePenalCode.js) and inserts
 * the articles into the MongoDB LegalContent collection.
 *
 * Usage:
 *   node backend/seedLegalContent.js
 *
 * Options:
 *   --clear   Drop all existing LegalContent documents before seeding
 */

import mongoose from 'mongoose'
import fs from 'fs'
import path from 'path'
import { fileURLToPath } from 'url'
import dotenv from 'dotenv'

const __filename = fileURLToPath(import.meta.url)
const __dirname = path.dirname(__filename)

dotenv.config({ path: path.join(__dirname, '.env') })

const PARSED_LAWS_PATH = path.join(__dirname, '..', 'Documents', 'parsedLaws.json')
const CLEAR_FLAG = process.argv.includes('--clear')

// ─── LegalContent Schema (inline to avoid circular deps) ─────────────────────

import LegalContent from './src/models/LegalContent.js'

// ─── Seeder Logic ─────────────────────────────────────────────────────────────

async function seed() {
  console.log('━'.repeat(60))
  console.log('  Digital Legal Aid — LegalContent Seeder')
  console.log('━'.repeat(60))

  // Connect to MongoDB
  const mongoUri = process.env.MONGODB_URI
  if (!mongoUri) {
    console.error('❌ MONGODB_URI not found in .env file')
    console.error('   Make sure backend/.env exists with MONGODB_URI set.')
    process.exit(1)
  }

  console.log(`\n🔌 Connecting to MongoDB...`)
  await mongoose.connect(mongoUri)
  console.log('✅ Connected to MongoDB\n')

  // Read parsedLaws.json
  if (!fs.existsSync(PARSED_LAWS_PATH)) {
    console.error(`❌ parsedLaws.json not found at: ${PARSED_LAWS_PATH}`)
    console.error('   Run parsePenalCode.js first: node backend/parsePenalCode.js Documents/penalcode2018.pdf')
    await mongoose.disconnect()
    process.exit(1)
  }

  const raw = fs.readFileSync(PARSED_LAWS_PATH, 'utf8')
  const parsed = JSON.parse(raw)

  // Support both old format { metadata, articles } and new combined format
  const articles = Array.isArray(parsed) ? parsed : parsed.articles
  const metadata = parsed.metadata || { source: 'unknown', parsed_at: new Date().toISOString() }

  console.log(`📋 Parsed at: ${metadata.parsed_at}`)
  if (metadata.documents) {
    console.log(`📋 Documents included:`)
    metadata.documents.forEach(d => console.log(`     • ${d.type}: ${d.articles} articles`))
  } else {
    console.log(`📋 Source: ${metadata.source}`)
  }
  console.log(`📋 Total articles to seed: ${articles.length}\n`)

  // Optionally clear existing data
  if (CLEAR_FLAG) {
    const deleted = await LegalContent.deleteMany({})
    console.log(`🗑️  Cleared ${deleted.deletedCount} existing LegalContent documents\n`)
  }

  // Map validated crime types (LegalContent schema enum)
  const VALID_CRIME_TYPES = new Set([
    'Theft', 'Assault', 'GBV', 'Fraud', 'Property Damage',
    'Murder', 'Drug', 'Corruption', 'Other'
  ])

  // Build LegalContent documents from parsed articles
  const documents = articles.map(article => ({
    crimeType: VALID_CRIME_TYPES.has(article.crime_type) ? article.crime_type : 'Other',
    articleNumber: article.article_number,
    sourceDocument: article.source_document || metadata.source || 'Penal Code 2018',
    relevantForCitizens: true,
    originalText: {
      en: article.english_text,
      rw: article.kinyarwanda_text || ''
    },
    simplifiedExplanation: {
      en: article.simplified_english,
      rw: article.kinyarwanda_text
        ? article.kinyarwanda_text.substring(0, 300) + '...'
        : article.simplified_english
    },
    reportingSteps: article.reporting_steps.map(step => ({
      stepNumber: step.step_number,
      description: { en: step.description, rw: step.description }
    })),
    requiredEvidence: article.required_evidence.map(evidence => ({
      en: evidence, rw: evidence
    })),
    whereToReport: {
      en: article.where_to_report,
      rw: article.where_to_report
    },
    tags: article.keywords || [],
    keywords: article.keywords || [],
    viewCount: 0
  }))

  // Deduplicate: same (articleNumber + sourceDocument) → keep the one with longest text
  const deduped = new Map()
  for (const doc of documents) {
    const key = `${doc.sourceDocument}::${doc.articleNumber}`
    const existing = deduped.get(key)
    const len = (doc.originalText.en || '').length
    const existingLen = existing ? (existing.originalText.en || '').length : 0
    if (!existing || len > existingLen) {
      deduped.set(key, doc)
    }
  }
  const uniqueDocs = [...deduped.values()]
  console.log(`📋 After deduplication: ${uniqueDocs.length} unique articles (removed ${documents.length - uniqueDocs.length} duplicates)\n`)

  // Use bulkWrite with ordered:false for fast upserts
  // Key on (articleNumber + sourceDocument) so same article numbers from different laws don't overwrite
  console.log('⏳ Inserting into MongoDB (bulk upsert)...')

  const ops = uniqueDocs.map(doc => ({
    updateOne: {
      filter: { articleNumber: doc.articleNumber, sourceDocument: doc.sourceDocument },
      update: { $set: doc },
      upsert: true
    }
  }))

  const result = await LegalContent.bulkWrite(ops, { ordered: false })

  const inserted = result.upsertedCount
  const updated  = result.modifiedCount

  console.log('\n📊 Seeding results:')
  console.log(`   ✅ Inserted: ${inserted} new articles`)
  console.log(`   🔄 Updated:  ${updated} existing articles`)

  // Per-document breakdown
  const bySource = {}
  uniqueDocs.forEach(d => { bySource[d.sourceDocument] = (bySource[d.sourceDocument] || 0) + 1 })
  console.log('\n📂 Articles per document in this run:')
  Object.entries(bySource).forEach(([src, n]) => console.log(`   • ${src.padEnd(35)} ${n}`))

  const total = await LegalContent.countDocuments()
  console.log(`\n📦 Total LegalContent documents in DB: ${total}`)

  await mongoose.disconnect()
  console.log('\n✅ Done. MongoDB disconnected.\n')
}

seed().catch(err => {
  console.error('❌ Seeder failed:', err.message)
  console.error(err.stack)
  process.exit(1)
})
